version: '3.8'

services:
  tp-mysql:
    image: mysql
    container_name: tp-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - tp-docker-mysql-phpmyadmin

  tp-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: tp-phpmyadmin
    environment:
      PMA_HOST: tp-mysql
    ports:
      - "8081:80"
    networks:
      - tp-docker-mysql-phpmyadmin

networks:
  tp-docker-mysql-phpmyadmin:
    driver: bridge
